#ifndef _ITEMS_HPP_
#define _ITEMS_HPP_

enum Items {
	None,
	Aguav_Berry,
	Assault_Vest,
	Babiri_Berry,
	Charti_Berry,
	Chilan_Berry,
	Choice_Band,
	Choice_Specs,
	Chople_Berry,
	Coba_Berry,
	Colbur_Berry,
	Figy_Berry,
	Haban_Berry,
	Iapapa_Berry,
	Kasib_Berry,
	Kebia_Berry,
	Life_Orb,
	Mago_Berry_,
	Occa_Berry,
	Passho_Berry,
	Payapa_Berry,
	Rindo_Berry,
	Roseli_Berry,
	Shuca_Berry,
	Sitrus_Berry,
	Tanga_Berry,
	Wacan_Berry,
	Wiki_Berry,
	Yache_Berry,
	// Gen 9 items (appended to preserve existing enum values)
	Booster_Energy,
	Clear_Amulet,
	Covert_Cloak,
	Loaded_Dice,
	Mirror_Herb,
	Punching_Glove,
	Eviolite,
	// Type-boosting items (×1.2)
	Black_Belt,
	Black_Glasses,
	Charcoal,
	Dragon_Fang,
	Fairy_Feather,
	Hard_Stone,
	Magnet,
	Metal_Coat,
	Miracle_Seed,
	Mystic_Water,
	Never_Melt_Ice,
	Poison_Barb,
	Sharp_Beak,
	Silk_Scarf,
	Silver_Powder,
	Soft_Sand,
	Spell_Tag,
	Twisted_Spoon
};

#endif